apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cafe-frontend
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://cafe-management.cafe-backend.svc.cluster.local:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
