namespace: cafe-management

mysql:
  image:
    repository: gfrgt/mysql
    tag: latest
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    database: cafemanagement
    user: testuser
    password: testuser@123
    rootPassword: admin123

backend:
  image:
    repository: gfrgt/backend
    tag: latest
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: true
  host: vprofile.bits.work.gd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
