namespace: cafe-backend

# Backend Spring Boot (dynamic)
backend:
  name: cafe-backend
  image:
    repository: "{{ .Values.global.ecrRegistry }}/cafe-backend"
    tag: "{{ .Values.global.imageTag }}"
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# MySQL (static Docker Hub image you already pushed with data)
mysql:
  name: mysql-standalone
  image:
    repository: gfrgt/mysql
    tag: "latest"
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    database: cafemanagement
    user: testuser
    password: testuser@123
    rootPassword: admin123

# Global dynamic values for CI/CD
global:
  ecrRegistry: ""       # set dynamically from GitHub Actions
  imageTag: "latest"    # set dynamically from GitHub Actions

# Ingress config
ingress:
  enabled: false
  host: ""
  annotations: {}
