namespace: cafe-backend

global:
  ecrRegistry: ""
  imageTag: "latest"

backend:
  name: cafe-backend
  image:
    repository: ""
    tag: ""
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

mysql:
  name: mysql-standalone
  image:
    repository: gfrgt/mysql
    tag: latest
  persistence:
    enabled: false
    size: 1Gi
  credentials:
    database: cafemanagement
    user: testuser
    password: testuser@123
    rootPassword: admin123

ingress:
  enabled: false
  host: ""
  annotations: {}
