apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-management
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: cafe-management
  template:
    metadata:
      labels:
        app: cafe-management
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        command: ['sh', '-c', 'until mysql -h mysql-standalone -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"; do echo waiting for mysql; sleep 2; done']
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: DB_PASSWORD
      containers:
      - name: springboot-docker-container
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-standalone:3306/{{ .Values.mysql.credentials.database }}?allowPublicKeyRetrieval=true&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: DB_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cafe-secrets
              key: DB_PASSWORD
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
