apiVersion: v1
kind: Service
metadata:
  name: cafe-management
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cafe-management
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 8080
  type: {{ .Values.backend.service.type }}
