namespace: cafe-backend

# Backend Spring Boot (dynamic)
backend:
  name: cafe-backend
  image:
    repository: "{{ .Values.global.ecrRegistry }}/cafe-backend"  # dynamic from GitHub Actions
    tag: "{{ .Values.global.imageTag }}"                           # dynamic from GitHub Actions
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# MySQL (static Docker Hub image)
mysql:
  name: mysql-standalone
  image:
    repository: gfrgt/mysql         # Docker Hub image
    tag: "latest"
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    database: cafemanagement
    user: testuser
    password: testuser@123
    rootPassword: admin123

# Global dynamic values for CI/CD
global:
  ecrRegistry: ""      # Set dynamically from GitHub Actions
  imageTag: "latest"   # Set dynamically from GitHub Actions
