apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
