apiVersion: v2
name: cafe-frontend
description: Helm chart for Cafe Management System Frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: cafe-team
keywords:
  - angular
  - frontend
  - cafe-management
