namespace: cafe-frontend

global:
  ecrRegistry: ""        # Set dynamically via CI/CD
  imageTag: "latest"     # Set dynamically via CI/CD
  nginx:
    config:
      backendUrl: http://cafe-backend.cafe-backend.svc.cluster.local:8080

frontend:
  name: frontend
  image:
    repository: ""
    tag: ""
    pullPolicy: Always

  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  service:
    type: LoadBalancer      # Changed to LoadBalancer for external browser access
    port: 80
    targetPort: 80

  probes:
    readiness:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 5
    liveness:
      path: /
      initialDelaySeconds: 15
      periodSeconds: 10

ingress:
  enabled: true
  className: nginx
  host: vprofile.bits.work.gd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []
